### ISSUE TITLE
--private, --private-api, VPC peering and VPN

### ISSUE THREAD

**Issue by nzoschke** [convox/site#100]
Private networking has landed: https://github.com/convox/rack/pull/350
## Docs
- [x] Document Private Network Config
  - [ ] VPC peering

**Comment by matthewford** [comment]
While it mentions the additional cost of the NAT gateways as an indication it's at least $100 a month

**Comment by soulshake** [comment]
@nzoschke `--private` is documented [here](https://convox.com/docs/private-networking/). Does that cover it? What is `--private-api`?
