### ISSUE TITLE
Feedback on Getting Started Guide

### ISSUE THREAD

**Issue by nzoschke** [convox/site#103]
From yuval@convox.com:
1. Link does not function as hyperlink at the top of the page
2. After Creating an IAM User - there is no “next”, it was not obvious what to do next
   on Grid it does not say who is currently logged in (there is only a logout button)
3. “When the installation is complete you can safely delete the user.” Why would I want to delete the user? It is not clear. 
4. Installing a rack: it was not clear enough what details to provide, but one can guess
   no installation status/progress on main page of Grid when installing a rack.
5. CLI did not work as per instruction (curl downloaded an empty zip file)
6. Grid API key - people who are new to Grid need more instructions where to find it
7. What is the sinatra app? (I am only told to clone and create it…) How do I use it?
8. Perhaps a youtube/vimeo movie to show how to deploy?
9. convox services create postgres --name pg1   - no progress indication...
10. Also, I’d be curious to learn what other alternatives would look like (pros/cons) to deploy Sinatra…
11. What’s this? “To deploy these changes run `convox releases promote RQLNRQJEHJZ`” Never saw “Releasing... OK, RANLOWQFMRF    only Promoting RRPHNBZPDDG... UPDATING ; Never saw Waiting for app...
12. What/where is the connection between my AWS account, Grid, my rack and the app I just deployed? 
13. Explanation on how it scales automatically(?) - all the goodies of AWS without the complexity - secure, VPC, etc. → need to show the value Convox provided (see also 12 above)
14. Never saw http://sinatra-1233165548.us-east-1.elb.amazonaws.com:3000  but this one  https://convox-1452950246.us-west-2.elb.amazonaws.com:5000/

**Comment by pfeilbr** [comment]
[docs/developing-locally](http://convox.com/docs/developing-locally/) has no mention of the docker prerequisite.  With your target audience being a more hardcore developer type (assumed), docker already being installed may be implied, but might be good to be explicit.
