### ISSUE TITLE
API documentation missing from site

### ISSUE THREAD

**Issue by burningion** [convox/site#127]
Looking at the docs on [convox rack](http://convox.github.io/docs/rack/), first link for the [Convox API](http://convox.github.io/docs/rack/) leads to 404.

**Comment by mwarkentin** [comment]
The API documentation is available here: https://convox.com/api

However, the styling is totally busted:

![](https://mwarkentin-snaps.s3.amazonaws.com/httpsconvox.comapi_2016-11-21_12-37-19.png)

It would also be great to get some basic docs about how to leverage the API (authentication, examples, etc.)

**Comment by soulshake** [comment]
Update: the link to the [API docs](https://convox.com/api) is fixed, and the styling is fixed too.

We're working on some more API docs, and to get the "Try it now!" buttons to work, so stay tuned :)

**Comment by soulshake** [comment]
Update 2: API doc works now, resolved by #422. Thanks!
