### ISSUE TITLE
AWS simple cost calculator link with configuration

### ISSUE THREAD

**Issue by nicolas-brousse** [convox/site#14]
Hi,

I guess it could be nice to have if the link "AWS simple cost calculator" show the calculator with configuration. Like this it is simple for anybody to add some configuration and have a preview of the cost.

**Comment by ddollar** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;k0C0DA7y&#x2F;129-aws-stack-cost-calculator"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> AWS stack cost calculator</a>

**Comment by pfeilbr** [comment]
"This configuration costs $85/month according to the AWS simple cost calculator." is most likely dynamically pulling the latest costs for a given region, but you may want to specify the region the cost per month is based on.

**Comment by soulshake** [comment]
Our [Rack cost](https://convox.com/docs/rack-cost/#default-aws-resources) doc has been updated with as much detail as is possible, given AWS dynamic pricing.
