### ISSUE TITLE
Add more detail about AWS layout

### ISSUE THREAD

**Issue by ddollar** [convox/site#185]
Need to add more information about the default Rack configuration and how we take advantage of AWS to provide a stable deployment environment.
- Explain ECS clusters and how capacity, scheduling works
- Explain autoscaling group and how it handles AZ failure
- Explain logging infrastructure
- Explain build system

**Comment by paulca** [comment]
When I ran `convox uninstall` I was both shocked, amazed and delighted at the sheer number of things that were set up ... but I was a bit surprised.

Before I pressed "install rack", it would have been good to have a list of things that were about to happen, just so I knew what I was doing ahead of time.

**Comment by rosskevin** [comment]
- how to shut down a rack when not in use (save money on instances i.e. staging) where spin-up time isn't an issue

**Comment by clay-to-n** [comment]
Would be nice also to mention what sticks around after convox uninstall (S3 buckets, for instance).

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Guide: Deploy / Rack](https://trello.com/c/nElN6t4G/1104-guide-deploy-rack)

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Docs: Rack](https://trello.com/c/aBDauB86/1141-docs-rack)
