### ISSUE TITLE
switching between convox accounts with convox login

### ISSUE THREAD

**Issue by frsechet** [convox/site#189]
According to the doc (https://console.convox.com/grid/user/profile), if I do `convox login console.convox.com`, I will get asked for a password. I can then enter my API key and everything should run smoothly.

However, if I need to switch between convox _accounts_, where I'm logged in on one account and need to login on the second account, entering `convox login console.convox.com` will just return `Logged in successfully.`.

The way to go is `convox login console.convox.com --password=MY_API_KEY`, but, as this doesn't appear anywhere, can really confuse users.

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Docs: Clarify the notion of "logging in" / switch racks](https://trello.com/c/FeHjGyjc/1267-docs-clarify-the-notion-of-logging-in-switch-racks)
