### ISSUE TITLE
Underscore not allowed in process names

### ISSUE THREAD

**Issue by mattmanning** [convox/site#244]
This should be documented in the Docker Compose file doc and we should make sure our examples don't use underscores.

https://github.com/convox/rack/pull/1165

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;eK5PWkMh&#x2F;633-underscores-not-allowed-in-process-names"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Underscores not allowed in process names</a>

**Comment by soulshake** [comment]
This is now documented at https://convox.com/docs/docker-compose-file/#service-names.
