### ISSUE TITLE
Overview Feedback

### ISSUE THREAD

**Issue by garyrob** [convox/site#297]
When I ran "convox doctor" the response was:
### Setup

[✓] Convox CLI version  
[✓] Docker running  
[✓] Docker up to date  
[✓] Docker pull hello-world works    
### Build: Image

[X] Dockerfile found  
A Dockerfile is required to build an Image
https://convox.com/guide/build/

It would have been nice if the documentation had mentioned that that the user would get that error.

**Comment by soulshake** [comment]
Thanks for pointing this out. There's now a warning about this at the bottom of https://convox.com/guide/.
