### ISSUE TITLE
Image sizing

### ISSUE THREAD

**Issue by mattmanning** [convox/site#310]
It seems like some recent styling changes have had a side-effect on image sizing. Previously images were scaled down to fit, but now I'm seeing some huge images that are bleeding out of the main layout. Look at https://convox.com/docs/rack/ and https://convox.com/docs/workflows/ for example.

**Comment by mattmanning** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Image sizing on site](https://trello.com/c/76jHKLLT/930-image-sizing-on-site)

**Comment by mwarkentin** [comment]
+1 - noticed on these pages as well:

* https://convox.com/docs/audit/
* https://convox.com/docs/access-control/

**Comment by soulshake** [comment]
Fixed in #311.
