### ISSUE TITLE
List possible ns and at values in Logs documentation

### ISSUE THREAD

**Issue by idris** [convox/site#315]
`convox logs` prints logs with `ns=` and `at=` in them, but there is no documentation on what the values mean, or what the possible values are.

It would be nice to have a list of possible values in the docs, so we can navigate logs more easily.

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [docs: convox logs](https://trello.com/c/upE87Ybb/1137-docs-convox-logs)
