### ISSUE TITLE
Services should have instructions for running in dev as well as prod

### ISSUE THREAD

**Issue by idris** [convox/site#321]
Currently the [Services sections](https://convox.com/docs/s3/) just explains how to create services in production and use them in your app.

I think these pages should also explain how to simulate the service in dev, so you’d have documentation for the prod and dev setup in the same place

So, for example, in the [S3 docs](https://convox.com/docs/s3/), I’d expect all the `convox services create s3` stuff, but then I’d also want to see an explanation of how to use [convox/aws-s3](https://github.com/convox/aws-s3) to simulate it locally.

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/convox/site/issues/321](https://trello.com/c/4crE9mfL/1138-https-github-com-convox-site-issues-321)

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Docs: Local services](https://trello.com/c/4crE9mfL/1138-docs-local-services)
