### ISSUE TITLE
Convox services create should provide better error messages

### ISSUE THREAD

**Issue by alex-kaufman** [convox/site#324]
I ran the command `convox services create postgres --name=db-v2 --allocated-stoage=40 --instance-type=db.t2.medium --private --version=9.5.4`, which has a typo (`--allocated-stoage` should be `--allocated-storage`). 

**Actual behavior**
The creation of the resource succeeds and uses the default value of 10 for allocated storage.  

**Desired Behavior**
Do not create the new service and report to the user that an unrecognized flag was provided.

**Comment by soulshake** [comment]
This issue was moved to convox/rack#1383
