### ISSUE TITLE
API Keys Feedback

### ISSUE THREAD

**Issue by mrengine** [convox/site#325]
You write: `The Rack may be temporarily unavailable while the change takes effect.`. Truth is it takes up to an hour. There is not notice... no logs... nothing. It's just "click reload for an hour like an idiot`. Come guys get some notifications for god's sake.

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Docs: Keyroll](https://trello.com/c/NQZTU11p/1229-docs-keyroll)
