### ISSUE TITLE
Advanced Topics

### ISSUE THREAD

**Issue by soulshake** [convox/site#335]
_From @nzoschke on October 17, 2016 22:12_

This guide covers the basics. It should also offer links to some advanced topics. Some ideas...
- Picking A Base Image
- Vendoring Private Dependencies
- Optimizing Image Build Times
- Multiple Dockerfiles
- Balancer Header Injection
- Balancer SSL Certificates
- End-to-End Encryption
- Development Database Persistence
- Data Migrations
- [Twelve-Factor Backing Services](https://12factor.net/backing-services)
- Graceful Handling of Linked Service Unavailability
- Avoiding Service Discovery
- Container File Syncing

_Copied from original issue: convox/guide#4_

**Comment by mwarkentin** [comment]
Capacity planning: many small instances vs. several large instances and the trade offs between them. 

Sizing containers: coming up with good CPU/memory limits

How to support real time (web) and async (worker) containers without impacting user performance.
