### ISSUE TITLE
Document all Rack Parameters

### ISSUE THREAD

**Issue by soulshake** [convox/site#338]
[This page](https://convox.com/docs/rack-parameters/) documents the following Rack parameters:

* Autoscale
* BuildMemory
* InstanceBootCommand
* InstanceCount
* InstanceRunCommand
* InstanceType
* Internal
* Private
* PrivateApi
* VolumeSize

Which, if any, of [these others](https://github.com/convox/rack/blob/b7d9a114d5cc5f0a2843b89413067466aa41bc94/provider/aws/dist/rack.json#L176) should be added to that page in the docs?

* "Ami"
* "ApiCpu"
* "ApiMemory"
* "BuildCpu"
* "BuildImage"
* "ClientId"
* "ContainerDisk"
* "Development"
* "Encryption"
* "ExistingVpc"
* "InstanceUpdateBatchSize"
* "Key"
* "Password"
* "Subnet0CIDR"
* "Subnet1CIDR"
* "Subnet2CIDR"
* "SubnetPrivate0CIDR"
* "SubnetPrivate1CIDR"
* "SubnetPrivate2CIDR"
* "SwapSize"
* "Version"
* "VPCCIDR"
* "Tenancy"

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Document all Rack parameters?](https://trello.com/c/tIq7H0KV/1131-document-all-rack-parameters)

**Comment by mwarkentin** [comment]
+1

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Docs: Rack](https://trello.com/c/aBDauB86/1141-docs-rack)
