### ISSUE TITLE
Introduction Feedback

### ISSUE THREAD

**Issue by peldi** [convox/site#346]
'convox doctor' no longer exists? I'm using convox client: 20160919194401

**Comment by soulshake** [comment]
@peldi `convox doctor` was introduced in a later version of `convox` than the one you're running.

```
$ convox update
Updating convox/proxy: OK
Updating convox: OK, 20161111173317

$ convox doctor
### Setup
[✓] Convox CLI version    
[✓] Docker running    
[✓] Docker up to date    
[✓] Docker pull hello-world works    
[snip]
```
Can you try running `convox update` and see if that helps?

**Comment by peldi** [comment]
Oops! :) I tried but I get stuck on "Updating convox/proxy:"....I even left
it on all night. Is there a --verbose option?
