### ISSUE TITLE
SSL Feedback

### ISSUE THREAD

**Issue by scottmessinger** [convox/site#418]
In the docs, two options for certificates are offered: generate one from AWS (via `convox certs generate`) or purchase a certificate. After reading the section, I was left wondering: what's the pro/cons between generating a certificate from AWS and purchasing one? I assume purchasing a certificate provides more control, but I'm not sure how it would benefit me.

**Comment by matthewford** [comment]
I think if you generate a certificate, it is auto renewing, but i'm not sure if you can download it out of AWS.

**Comment by mwarkentin** [comment]
Correct, ACM certs are not downloadable.
