### ISSUE TITLE
Aurora Feedback

### ISSUE THREAD

**Issue by seivan** [convox/site#430]
Any chance we could use Aurora PostgreSQL (that's currently being tested) instead of Posgres? 
Or could we define our own resources amongst AWS products? 
To rephrase, how could we add our own resources as a Convox Resource?

**Comment by soulshake** [comment]
Hi @seivan, sorry we missed this. You could use Aurora PostgreSQL instead of Postgres, but you'd need to manage it yourself in AWS for now. We'd need a patch to be able to add such things as a Convox resource, but that probably wouldn't be too hard (if one were so inclined!).
