### ISSUE TITLE
Introduction ideas

### ISSUE THREAD

**Issue by mattmanning** [convox/site#496]
From @nzoschke's comment at https://github.com/convox/site/pull/493#issuecomment-277318859

- [ ] Make the first docs page "Getting Started".
- [ ] In "Overview" call out philosophy highlights in one paragraph  and link to a philosophy page for full details
- [ ] Import "Getting Started" content as "Quick Start" section
- [ ] Simplify "Getting Started" as much as possible for the happy path.
- [ ] Write as if the UI is very intuitive and has well-designed flow flow. Instead of a paragraph about live-updating, say "Click Install Convox. Configuring AWS will take about 10 minutes. During this you can set up the CLI.".  
- [ ] The links at the bottom for advanced topics are great. Add a link to advanced networking options.
- [ ] Drive product improvements around `convox apps create && watch convox apps info && convox deploy && watch convox apps info` to get first deploy

For example how great would it be if the doc was:

```bash
$ cd rails
$ convox deploy
Creating new app "rails"... OK

Building rails...
Creating tarball... OK
Uploading: 736.17 KB / 935.53 KB [=================>----]  78.69 % 1s 
Authenticating 132866487567.dkr.ecr.us-east-1.amazonaws.com: Login Succeeded
running: docker build
Step 1 : FROM convox/rails
Step 2 : COPY Gemfile /app/Gemfile
Step 3 : COPY Gemfile.lock /app/Gemfile.lock
Step 4 : RUN bundle install
...
DONE.

Deploying rails...
Creating image registry service... OK
Creating log service... OK
Creating load balancer services...
  rails-web-22KJ7UC-166046811.us-east-1.elb.amazonaws.com:80 (web)
  rails-web-22KJ7UC-166046811.us-east-1.elb.amazonaws.com:443 (web)
  internal-rails-database-KTJQAYI-i-451032694.us-east-1.elb.amazonaws.com:5432 (database)
OK
Starting containers... OK
Waiting for health checks to pass... OK
DONE.

```

## Example App

- [ ] convox/rails is not booting on my computer with a Docker reset

```bash
build    │ running: docker tag convox/postgres:latest rails/database
database │ running: docker run -i --rm --name rails-database -p 5432/tcp -v /Users/noah/.convox/volumes/rails/database/var/lib/postgresql/data:/var/lib/postgresql/data rails/database
web      │ running: docker run -i --rm --name rails-web --add-host database:172.17.0.9 -e DATABASE_SCHEME=postgres -e DATABASE_HOST=172.17.0.9 -e DATABASE_PORT=5432 -e DATABASE_PATH=/app -e DATABASE_USERNAME=postgres -e DATABASE_PASSWORD=password -e DATABASE_URL=postgres://postgres:password@172.17.0.9:5432/app -p 0:4000/tcp -p 0:4001/tcp --cpu-shares 10 --memory 536870912 rails/web
database │ FATAL:  database files are incompatible with server
database │ DETAIL:  The data directory was initialized by PostgreSQL version 9.4, which is not compatible with this version 9.5.4.
```

**Comment by nzoschke** [comment]
I plan to turn the Console setup checklist into the following. I think the getting started doc should match this almost 100%.

---

You can follow these simple steps to set everything up, beginning with creating an organization. At any time you can click the Setup button to re-visit this page and review your progress.

- [ ] Create an organization
- [ ] Connect an AWS account
- [ ] Launch a private PaaS
- [ ] Connect the Convox CLI
- [ ] Deploy an app

Once you are familiar with deploying an application to Convox, you may want to:

- [ ] Connect a source control service
- [ ] Set up a continuous delivery workflow
- [ ] Invite your team

**Comment by nzoschke** [comment]
Should the getting started for deploy an app cover setting up a real redis or postgres resource?

It feels like that is a better real-world guide than going down the containerized redis/postgres path.

The downsides are that RDS or ElastiCache resources:

1. Are slow to provision
2. Costs $12/mo
3. Are a bit clunky to add to an app

1. can be addressed by instructing the user to do it right before or after `convox apps create`. 2. is a platform-wide concern, but doesn't seem to be a deal breaker for trials. 3 we should just fix in our product.

**Comment by nzoschke** [comment]
Some more QA on the getting started page

- [ ] Four bullet points (Signing up, Launching, Installing, Deploying) should link to page sections
- [ ] Page section anchors don't display the section header
- [ ] Install CLI intro is too long / detailed
- [ ] "securing your apps easy" typo
- [ ] eliminate "watch convox apps info" steps through product changes
- [ ] Deploy to convox should walk through an example app with "See Preparing An App for more details"
