### ISSUE TITLE
Combine custom JS and CSS into single, compressed files

### ISSUE THREAD

**Issue by gerritwh** [convox/site#572]
As in the title. 

I think it would be a good thing to reorganize and combine the several custom scripts and CSS files in order to achieve cleaner code and to reduce HTTP requests. 

Or: Take a real modular approach and load files only where they are need ([React](https://facebook.github.io/react/)?)

**Comment by soulshake** [comment]
I agree the assets need to be cleaned up. I have a feeling there's a lot of duplication in the CSS especially.

I don't know how I feel about combining them though. I wonder if there's a way to make jekyll do that, or to do it at build time.

I'm in favor of any approach that results in faster loading without making grepping the source more difficult (e.g. ~minification). I don't know what a modular approach would look like but would be happy to consider a PR with suggested improvements :)

**Comment by mwarkentin** [comment]
Also, keep in mind that w/ HTTP2 combining and minifying everything to reduce HTTP requests isn't (with some caveats) the most efficient method.

**Comment by gerritwh** [comment]
@soulshake There is a Jekyll plugin for that. For example https://github.com/stereobooster/jekyll-press (Haven't tried it yet). But you are right, compressing into single files would be the last step. First step should be some clean up.
