### ISSUE TITLE
[frontend] Inconsistency in link colors on homepage

### ISSUE THREAD

**Issue by gerritwh** [convox/site#582]
The author names of the testimonials and the "How Convox Works" titles appear as links, but they're not. I'd simply set them to #333333 to avoid confusion and keep things consistent.
Maybe work on the testimonials a little bit to reestablish some contrast: I think Merriweather italic would do a good job for that. Let me know if you'd like me to come up with a suggestion.

**Comment by soulshake** [comment]
:+1: Maybe @nzoschke has an opinion?
