### ISSUE TITLE
FAQ Doc

### ISSUE THREAD

**Issue by mattmanning** [convox/site#621]
Let's start a FAQ doc, even if it only has a couple of questions on it to start with. Here's one:

How to deal with "unable to place a task because no container instance met all of its requirements. Reason: No Container Instances were found in your cluster"

**Comment by mwarkentin** [comment]
Some others:

* Why is my rack in "converging" state?
* What do I do with DB containers when deploying to AWS and using RDS?
* Can I scale down my rack?
