### ISSUE TITLE
Document how to add an existing Rack

### ISSUE THREAD

**Issue by mattmanning** [convox/site#624]

**Comment by mattmanning** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Document how to add an existing Rack](https://trello.com/c/9aWuYlFd/2075-document-how-to-add-an-existing-rack)

**Comment by ianmalott** [comment]
https://github.com/convox/site/pull/630

**Comment by soulshake** [comment]
Resolved by #630
