### ISSUE TITLE
Running Locally Feedback

### ISSUE THREAD

**Issue by smingins** [convox/site#665]
Explain how to interact with the local resources.  I'm using Rails at the moment so the things I want to know is how to get a shell to the web server so I can rake commands or a rails console.

How can I access the database?

Also with the docker-compose.yml ... if in production we are using RDS and Redis with env variables set ... what should we be doing locally?  When I run convox init for example it creates a database section.

I have been doing this using docker and the container IDs but I'm not sure if that is the right approach or not.  How much docker do I need to know to use convox?

**Comment by soulshake** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Running Locally Feedback [site issue]](https://trello.com/c/C2Gs8khu/2272-running-locally-feedback-site-issue)

**Comment by soulshake** [comment]
Hi @smingins, thanks for this feedback. I'll see if we can get this page updated soon with more information.

To answer your question: If you have set up a remote resource, during local development you can either:
- proxy to the resource as described [here](https://convox.com/docs/about-resources/#via-proxy)
- Use the local containers, which will be automatic for linked services as described [here](https://convox.com/docs/environment#linking).

Either way, you'll want to [scale the remote services to `-1`](https://convox.com/docs/scaling/#scaling-down-unused-services) to avoid creating unnecessary remote containers and load balancers.
