### ISSUE TITLE
Supported AWS Regions Feedback

### ISSUE THREAD

**Issue by axyjo** [convox/site#700]
Hi -- is ca-central-1 on the roadmap? It seems to support everything needed

**Comment by nathany** [comment]
Though https://convox.com/docs/supported-aws-regions/ doesn't mention it, it sounds like [Amazon EFS](https://aws.amazon.com/efs/) is also required as per: https://github.com/convox/rack/pull/1454

**Comment by ddollar** [comment]
Actually ca-central-1 is supported. When EFS is not present shared volumes do not work but everything else should be fine. I have updated the docs.
