### ISSUE TITLE
removing convox from my account completely and deleting the default rack

### ISSUE THREAD

**Issue by ahmedatgithub** [convox/site#712]
two things:
- the 'convox install' command documentation does not tell you that in fact it does create a new default rack named "convox". And does not show you how to delete it, ( the "convox uninstall convox <region>" does fails to delete it with authentication errors that are clearly misleading)
- No where in the documentation does it say how  to COMPLETELY obliterate convox from your AWS account. (I know it shows you how to disable the integration, but I don't want to have to go and manually delete everything that convox created.)

**Comment by mwarkentin** [comment]
You can delete everything by removing the stacks which were created in AWS Cloudformation.
