### ISSUE TITLE
Hasura Blog Not Working

### ISSUE THREAD

**Issue by dayvough** [convox/site#799]
Hi, I'm trying [this](https://convox.com/blog/hasura_deployment) out now and it seems that convox doesn't allow underscores for resource names (couldn't find this anywhere in the docs re naming conventions). And now my Hasura container is unable to start as it can't find HASURA_GRAPHQL_DATABASE_URL.

**Comment by camerondgray** [comment]
Sorry for the out of date blog post and thanks for the catch! The post is updated in #801 and I'll close this issue once it's merged.

**Comment by camerondgray** [comment]
#801 merged
