### ISSUE TITLE
Adding Collaborators

### ISSUE THREAD

**Issue by nzoschke** [convox/site#88]
Document methods for sharing a rack.

> you can give them the API Key in ~/.convox/auth, but the best way is through https://grid.convox.com
> add your rack there then you can invite some collaborators

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;aM4xNRRp&#x2F;32-explain-collaborators"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Explain collaborators</a>
